name: release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Create .env secrets
        run: |
          echo "REACT_APP_SID_LIFE_TIME: ${{secrets.REACT_APP_SID_LIFE_TIME}}" >> .env
          echo "REACT_APP_PORTIS_ID: ${{secrets.REACT_APP_PORTIS_ID}}" >> .env
          echo "REACT_APP_FORTMATIC_KEY: ${{secrets.REACT_APP_FORTMATIC_KEY_TEST}}" >> .env
          echo "REACT_APP_SENTRY: ${{secrets.REACT_APP_SENTRY}}" >> .env
          echo "REACT_APP_TREZOR_URL: ${{secrets.REACT_APP_TREZOR_URL}}" >> .env
          echo "REACT_APP_TREZOR_EMAIL: ${{secrets.REACT_APP_TREZOR_EMAIL}}" >> .env
      - name: Add development .env params
        if: github.event.release.prerelease == true
        run: |
          echo "REACT_APP_API_URL: https://backend-dev.defihelper.io/api" >> .env
          echo "REACT_APP_WAVES_NODE_URL: https://nodes-testnet.wavesnodes.com" >> .env
          echo "REACT_APP_ADAPTERS_HOST: https://backend-dev.defihelper.io/adapters" >> .env
          echo "REACT_APP_BETA: true" >> .env
      - name: Add production .env params
        if: github.event.release.prerelease == false
        run: |
          echo "REACT_APP_API_URL: https://backend.defihelper.io/api" >> .env
          echo "REACT_APP_WAVES_NODE_URL: https://nodes.wavesnodes.com" >> .env
          echo "REACT_APP_ADAPTERS_HOST: https://backend.defihelper.io/adapters" >> .env
          echo "REACT_APP_BETA: true" >> .env
      - if: github.event.release.prerelease == true
        run: npm run build-dev
      - if: github.event.release.prerelease == false
        run: npm run build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-release
          path: |
            build

  publish:
    needs: build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Download build-release
        uses: actions/download-artifact@v2
        with:
          name: build-release
          path: ./build

      - name: Publish dev
        if: github.event.release.prerelease == true
        run: |
          mkdir -pv $GITHUB_WORKSPACE
          cp -rf $GITHUB_WORKSPACE ~/$GITHUB_REPOSITORY-dev.new
          mv ~/$GITHUB_REPOSITORY-dev ~/$GITHUB_REPOSITORY-dev.old
          mv ~/$GITHUB_REPOSITORY-dev.new ~/$GITHUB_REPOSITORY-dev
          rm -rf ~/$GITHUB_REPOSITORY-dev.old

      - name: Publish stable
        if: github.event.release.prerelease == false
        run: |
          mkdir -pv $GITHUB_WORKSPACE
          cp -rf $GITHUB_WORKSPACE ~/$GITHUB_REPOSITORY.new
          mv ~/$GITHUB_REPOSITORY ~/$GITHUB_REPOSITORY.old
          mv ~/$GITHUB_REPOSITORY.new ~/$GITHUB_REPOSITORY
          rm -rf ~/$GITHUB_REPOSITORY.old

  cloudflare-purge:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Purge cloudflare cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
